### PR TITLE
Adapt for Jenkins 2.264+ usage of div-based layout.

### PR DESCRIPTION
**Pull request by bdragon28**
Adapted from the JENKINS-64078 fix.

This fixes scrambled layout when running on Jenkins 2.264 and newer.

### CODE REVIEW

**Comment by bdragon28** [comment]
Hmm, interface is still broken for creation. Tinkering some more.

**Comment by kamaliang** [comment]
Hi, have you solved this problem  already ? I also had this problem, can you please share? Thank you very much !!!

**Comment by bdragon28** [comment]
I haven't gotten around to debugging the creation interface yet, sorry for the delay.

It was low priority for me as I'm using jenkins job builder to do job creation. Will try to get to it sometime this weekend.

**Comment by bdragon28** [comment]
Strange, I'm now not able to reproduce the problem I was having with the creation interface. Maybe there's some caching related problem that was causing it.

**Comment by JustOneMoreBlock** [comment]
@bdragon28 Any updates? We are having the same issue preventing us from saving.

**Comment by kamaliang** [comment]
> Strange, I'm now not able to reproduce the problem I was having with the creation interface. Maybe there's some caching related problem that was causing it.

Hi, i cleaned the browser's cache , all the job using the publish-over-ftp-plugin still have this problem, confusing~

**Comment by JustOneMoreBlock** [comment]
> @bdragon28 Any updates? We are having the same issue preventing us from saving.

I just compiled @bdragon28 version. You can find the hpi file and upload it.

Works fine for me.

**Comment by oleg-nenashev** [comment]
My bad. I have merged https://github.com/jenkinsci/publish-over-ftp-plugin/pull/9 without noticing this PR

**Comment by oleg-nenashev** [comment]
Basically the changes are identical. I will close this one, because #9 has been already merged.
Anyway, thanks a lot for your contribution @bdragon28 ! Will be more careful with merges

**Pull request closed without merging**
